package neurorouter

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"strings"
	"sync"
)

// WorkflowDetector tracks tool call sequences and identifies recurring patterns.
type WorkflowDetector struct {
	mu sync.Mutex

	// Sequence tracking.
	currentSeq []string                     // current session's tool call sequence
	seqCounts  map[string]*detectedWorkflow // sequence hash → workflow
	minSteps   int                          // minimum steps to consider (default 3)
	minOccur   int                          // minimum occurrences to suggest (default 3)
}

type detectedWorkflow struct {
	Steps     []string
	Count     int
	Hash      string
	Suggested bool // already suggested to user
}

// WorkflowSuggestion is emitted when a recurring workflow is detected.
type WorkflowSuggestion struct {
	Hash      string   `json:"hash"`
	Steps     []string `json:"steps"`
	Count     int      `json:"count"`
	SkillName string   `json:"skill_name"` // suggested skill name
	SkillBody string   `json:"skill_body"` // generated skill definition
}

// NewWorkflowDetector creates a detector with default thresholds.
func NewWorkflowDetector() *WorkflowDetector {
	return &WorkflowDetector{
		seqCounts: make(map[string]*detectedWorkflow),
		minSteps:  3,
		minOccur:  3,
	}
}

// toolCallRe extracts tool names from message content.
var toolCallRe = regexp.MustCompile(`"name"\s*:\s*"([^"]+)"`)

// RecordMessages extracts tool calls from messages and appends to current sequence.
func (wd *WorkflowDetector) RecordMessages(msgs []ChatMessage) {
	wd.mu.Lock()
	defer wd.mu.Unlock()

	for _, m := range msgs {
		if m.Role != "assistant" {
			continue
		}
		for _, match := range toolCallRe.FindAllStringSubmatch(m.Content, -1) {
			wd.currentSeq = append(wd.currentSeq, match[1])
		}
	}

	// Extract and count all subsequences of length >= minSteps.
	wd.extractSubsequences()
}

// extractSubsequences finds all subsequences in the current sequence.
func (wd *WorkflowDetector) extractSubsequences() {
	seq := wd.currentSeq
	if len(seq) < wd.minSteps {
		return
	}

	// Sliding window: check subsequences of length minSteps to min(len, 8).
	maxLen := len(seq)
	if maxLen > 8 {
		maxLen = 8
	}

	for windowSize := wd.minSteps; windowSize <= maxLen; windowSize++ {
		for i := 0; i <= len(seq)-windowSize; i++ {
			subseq := seq[i : i+windowSize]
			hash := hashSequence(subseq)

			if existing, ok := wd.seqCounts[hash]; ok {
				// Only count if this is a new occurrence (not overlapping).
				if i > 0 {
					existing.Count++
				}
			} else {
				steps := make([]string, len(subseq))
				copy(steps, subseq)
				wd.seqCounts[hash] = &detectedWorkflow{
					Steps: steps,
					Count: 1,
					Hash:  hash,
				}
			}
		}
	}
}

// Suggestions returns workflow suggestions for sequences that exceed the threshold.
func (wd *WorkflowDetector) Suggestions() []WorkflowSuggestion {
	wd.mu.Lock()
	defer wd.mu.Unlock()

	var suggestions []WorkflowSuggestion

	for _, wf := range wd.seqCounts {
		if wf.Count >= wd.minOccur && !wf.Suggested {
			name := generateSkillName(wf.Steps)
			suggestions = append(suggestions, WorkflowSuggestion{
				Hash:      wf.Hash,
				Steps:     wf.Steps,
				Count:     wf.Count,
				SkillName: name,
				SkillBody: generateSkillBody(name, wf.Steps),
			})
		}
	}

	return suggestions
}

// MarkSuggested marks a workflow as already suggested (won't suggest again).
func (wd *WorkflowDetector) MarkSuggested(hash string) {
	wd.mu.Lock()
	defer wd.mu.Unlock()

	if wf, ok := wd.seqCounts[hash]; ok {
		wf.Suggested = true
	}
}

func hashSequence(steps []string) string {
	h := sha256.Sum256([]byte(strings.Join(steps, "→")))
	return hex.EncodeToString(h[:8])
}

func generateSkillName(steps []string) string {
	// Use abbreviated tool names joined by hyphens.
	abbrevs := make([]string, 0, len(steps))
	seen := make(map[string]bool)
	for _, s := range steps {
		lower := strings.ToLower(s)
		if !seen[lower] {
			abbrevs = append(abbrevs, lower)
			seen[lower] = true
		}
	}
	name := strings.Join(abbrevs, "-")
	if len(name) > 30 {
		name = name[:30]
	}
	return name
}

func generateSkillBody(name string, steps []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Skill: %s\n", name)
	fmt.Fprintf(&b, "# Auto-detected workflow (%d steps)\n", len(steps))
	b.WriteString("# Generated by neurorouter workflow detection\n\n")

	for i, step := range steps {
		fmt.Fprintf(&b, "# Step %d: %s\n", i+1, step)
	}

	b.WriteString("\n# Suggested workflow name: " + name + "\n")
	b.WriteString("# Review and install this workflow in your client or local tooling.\n")
	return b.String()
}
